# Site settings
name: The Chronicle of a ColdFusion Expatriate
title: The Chronicle
subtitle: of a ColdFusion Expatriate
author: Aaron Bieber
bio: >
  Hi, I'm Aaron Bieber. Once, long ago, I wrote ColdFusion for a living. Now I
  lead software engineers at HubSpot in Boston.
email: aaron@aaronbieber.com
description:
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.aaronbieber.com" # the base hostname & protocol for your site
twitter_username: aaronbieber
github_username:  aaronbieber
paginate: 5
excerpt_separator: ~~MORE~~
recent_posts: 5
date_format_short: "%B %d, %Y"
date_format_long: "%B %d, %Y"
disqus_short_name: aaronbieber
highlighter: rouge
exclude: [vendor]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

# Application settings
markdown: redcarpet
redcarpet:
  extensions:
    - no_intra_emphasis
    - fenced_code_blocks
    - autolink
    - tables
    - with_toc_data
    - smart
    - underline

gems:
  - rouge
  - jekyll-compass

# You will probably have to modify this path for your local configuration
# and I don't know any way around that, because, uh, this whole stack is
# essentially deprecated, so good luck.
sass:
  load_paths:
    - "/home/airborne/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/compass-core-1.0.3/stylesheets/"
