# Site settings
name: The Chronicle of a ColdFusion Expatriate
title: The Chronicle
subtitle: of a ColdFusion Expatriate
author: Aaron Bieber
bio: >
  Hi, I'm Aaron Bieber. Once, long ago, I wrote ColdFusion for a living. Now I
  write mostly PHP and I work for Wayfair in Boston.
email: aaron@aaronbieber.com
description: 
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://blog.aaronbieber.com" # the base hostname & protocol for your site
twitter_username: aaronbieber
github_username:  aaronbieber
paginate: 5
excerpt_separator: <!--more-->
recent_posts: 5
date_format_short: "%B %d, %Y"
date_format_long: "%B %d, %Y"
disqus_short_name: aaronbieber

# Build settings
markdown: redcarpet

gems:
  - jekyll-compass

sass:
  load_paths:
    - "/Users/airborne/.rbenv/versions/1.9.3-p374/lib/ruby/gems/1.9.1/gems/compass-0.12.2/frameworks/compass/stylesheets/"